version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_maven_app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - PYTHONUNBUFFERED=1
    command: ["sh", "-c", "pip install -r requirements.txt && python main.py"]
    mem_limit: 8g     # Limita a 8 GB de RAM
    cpus: 4.0   